### ISSUE TITLE
Sometimes totp code does not match

### ISSUE THREAD

**Issue by RCasatta** [hanskorg/google-authenticator-rust#1]
Calling `let code = auth.get_code(secret,0).unwrap();`
it's broken on my machine it always return the same code. This line https://github.com/hanskorg/google-authenticator-rust/blob/master/src/google_authenticator.rs#L102 return always 0
` 
If I try to pass the timestamp/30 instead of zero to the function sometime the code matches sometimes does not (probably rounding problem).

**Comment by hanskorg** [comment]
Thanks for your feedback, this bug fixed as you see 
```
(SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_secs() as u32) / 30 ;
```

As you known , the algorithm base on system time,  you can only to test code like 

```
//highly recommended discrepancy between 1 - 3
auth.verify_code(secret, "224124", 3, 0).unwrap()
```

**Comment by RCasatta** [comment]
the 0 bug is fixed, however I have still some discrepancy with another lib doing totp

```
        let totp = libreauth::oath::TOTPBuilder::new()
            .base32_key(&key_base32)
            .output_len(6)
            .finalize()
            .unwrap()
            .generate();
        use google_authenticator::GoogleAuthenticator;
        let auth = GoogleAuthenticator::new();
        let code = auth.get_code(&key_base32,0).unwrap();
        assert_eq!(totp, code);
```
this code sometimes pass, sometimes not

**Comment by hanskorg** [comment]
It not processed the significant bit of the  TOTP code, and now it's ok.

**Comment by RCasatta** [comment]
I can confirm in d4e3baf83dfde11dbb9e854ae1bb8564df0235a4 is fixed
