### ISSUE TITLE
rm println

### ISSUE THREAD

**Issue by swnb** [hanskorg/google-authenticator-rust#2]
thank you for this project, it helps me a lot

can you remove `println` code or replace it with [log](https://github.com/rust-lang-nursery/log)?

https://github.com/hanskorg/google-authenticator-rust/blob/d4e3baf83dfde11dbb9e854ae1bb8564df0235a4/src/google_authenticator.rs#L152-L153

**Comment by hanskorg** [comment]
so sorry for that,  new version(v0.1.8) later.
