### ISSUE TITLE
discrepancy works in 30s intervals?

### ISSUE THREAD

**Issue by JakubKoralewski** [hanskorg/google-authenticator-rust#8]
I've been playing around with the discrepancy parameter, and it definitely doesn't work in seconds, but in a larger time interval.
I think because the time is first divided by 30, and then you create the range [x-discrepancy, x+discrepancy], then the actual discrepancy is multiplied by 30? 

The description in the docs saying `The parameter discrepancy indicates number of seconds ago that a code may be generated. ` is incorrect, as what it really indicates is `the number of half-minutes ago and in the future that the code may be generated`?

https://github.com/hanskorg/google-authenticator-rust/blob/388f6933301df132aaf94982b7f15c9dce3f2e06/src/authenticator.rs#L208-L231

I think the docs or the usage of the parameter `discrepancy` should be modified, no?

**Comment by hanskorg** [comment]
As you said, it's not seconds, it indicates an acceptable time deviation between client and server,  by dividing by 30s.

**Comment by JakubKoralewski** [comment]
The documentation is a bit unclear on this then. `The parameter discrepancy indicates number of seconds ago that a code may be generated.` suggests that the discrepancy parameter itself is the number of seconds.

**Comment by hanskorg** [comment]
> suggests that the discrepancy parameter itself is the number of seconds.
In fact, The best practice is using a fixed time window, refer to [https://tools.ietf.org/html/rfc6238#section-5.2](https://tools.ietf.org/html/rfc6238#section-5.2)
